# Generated by Django 2.1.7 on 2020-03-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Female'), ('Male', 'Male')], default='m', max_length=10, verbose_name='Gender'),
        ),
    ]
