# Generated by Django 2.1.7 on 2020-03-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200319_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vin', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Vin')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('product_date', models.DateField(verbose_name='Product Date')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='car',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Customer'),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Manufacturer'),
        ),
    ]
