# Generated by Django 2.1.7 on 2020-03-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200319_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='product_date',
            field=models.DateField(auto_now_add=True, verbose_name='Product Date'),
        ),
    ]
